paths:
  time_series:       "{}"
  exposures_country: "{}"
  exposures_sector:  "{}"
  reports_dir:       "{}"
  runs_dir:          "{}"
  logs_dir:          "{}"
  run_checkpoint:    "{}"
  model_zip:         "{}"
  indexa_capital:    "{}"
